module.exports = {
  rules: {
    'import/no-default-export': 'off',
    'no-console': 'off',
    'no-param-reassign': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/consistent-type-definitions': 'off',
    'storybook/story-exports': 'off',
    '@typescript-eslint/array-type': 'off',
    'import/order': 'off',
    'no-implicit-coercion': 'off',
    'turbo/no-undeclared-env-vars': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/prefer-ts-expect-error': 'off',
    '@typescript-eslint/no-confusing-void-expression': 'off',
    '@typescript-eslint/prefer-function-type': 'off',
    '@typescript-eslint/no-unsafe-return': 'off',
    'eslint-comments/require-description': 'off',
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    "@typescript-eslint/no-non-null-assertion": "off",
    '@typescript-eslint/no-unnecessary-type-assertion': 'off',
    '@typescript-eslint/prefer-promise-reject-errors': 'off',
    '@typescript-eslint/no-unnecessary-condition': 'off',
    "@typescript-eslint/no-invalid-void-type": "off",
    "@typescript-eslint/no-floating-promises": "off",
    "@typescript-eslint/no-unsafe-call": "off",
    "no-nested-ternary":"off",
    eqeqeq: 'off',
  },
};
