// import { AppDataSource } from '@repo/database-service';
import './globals.css';
import '@repo/react-kit/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(`Root Layout`);
  // if (!AppDataSource.isInitialized) await AppDataSource.initialize();
  console.log(`Database Initialized`);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
